### ISSUE TITLE
tensorflow支持哪些版本

### ISSUE THREAD

**Issue by fanshunguo** [ymcui/Chinese-XLNet#41]
使用tensorflow 2.0有语法错误，tensorflow-gpu 1.13 eval步骤报错：
Traceback (most recent call last):
  File "run_classifier.py", line 1002, in <module>
    tf.app.run()
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 912, in main
    global_step = int(cur_filename.split("-")[-1])
ValueError: invalid literal for int() with base 10: '/home/workspace/models/xlnet_model.ckpt'
应该是不同版本的tensorflow模型文件的命名格式不匹配导致的 能否给一个tensorflow支持的版本范围

**Comment by ymcui** [comment]
https://github.com/zihangdai/xlnet#fine-tuning-with-xlnet

TF=1.13.1
